"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ÓÇ∂](cyan)\
$os\
$username\
[ÓÇ∞](bg:bright_red fg:cyan)\
$directory\
[ÓÇ∞](bg:neon_purple fg:bright_red)\
$git_branch\
$git_status\
[ÓÇ∞](bg:neon_blue fg:neon_purple)\
$c\
$cpp\
$golang\
$java\
$lua\
$mojo\
$odin\
$python\
$rust\
$zig\
[ÓÇ∞](fg:neon_blue)\
$line_break\
$character"""

palette = 'custom_colors'

[os]
disabled = false
style = "bg:cyan fg:black"

[os.symbols]
Windows = "Óúè"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "Û∞£á"
Artix = "Û∞£á"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"

[username]
show_always = true
style_user = "bg:cyan fg:black"
style_root = "bg:cyan fg:white"
format = '[ $user]($style)'

[directory]
style = "bg:bright_red fg:black"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = "Ôêò"
style = "bg:neon_purple"
format = '[[ $symbol $branch ](fg:black bg:neon_purple)]($style)'

[git_status]
style = "bg:neon_purple"
format = '[[($all_status$ahead_behind )](fg:black bg:neon_purple)]($style)'


[c]
symbol = "Óòû"
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[cpp]
symbol = "Óòù"
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[golang]
symbol = "Óòß"
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[java]
symbol = "Óâñ "
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[lua]
symbol = "Ó†¶"
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[mojo]
symbol = "üî•"
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[odin]
symbol = "√ò"
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[python]
symbol = "ÓòÜ"
style = "bg:neon_blue"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:black bg:neon_blue)]($style)'

[rust]
symbol = "Óû®"
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[zig]
symbol = "Ó£Ø"
style = "bg:neon_blue"
format = '[[ $symbol( $version) ](fg:black bg:neon_blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[‚ùØ](bold fg:cyan)'
error_symbol = '[‚ùØ](bold fg:bright_red)'
vimcmd_symbol = '[‚ùÆ](bold fg:cyan)'
vimcmd_replace_one_symbol = '[‚ùÆ](bold fg:neon_purple)'
vimcmd_replace_symbol = '[‚ùÆ](bold fg:neon_pruple)'
vimcmd_visual_symbol = '[‚ùÆ](bold fg:dark_yellow)'

[palettes.custom_colors]
white =       '#FFFFFF'
dark_grey=    '#4D4D4D'
light_grey=   '#B0B0B0'
black =       '#000000'
bright_red =  '#D90202'
dark_red =    '#720102'
rust_orange=  '#B5340E'
dark_yellow=  '#B58E0E'
neon_green=   '#2CB03C'
neon_purple=  '#932CB0'
light_purple= '#3E2CB0'
neon_blue=    '#3379D4'
cyan=         '#33D4C4'
